"""Add new action types

Revision ID: 63480e3e0d3f
Revises: eab3de4c1887
Create Date: 2026-08-30 15:51:13.792017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '63480e3e0d3f'
down_revision: Union[str, Sequence[str], None] = 'eab3de4c1887'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE actiontype ADD VALUE 'DYNAMIC_OFFER'")
        op.execute("ALTER TYPE actiontype ADD VALUE 'RESTRICTED_LINK'")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
