"""Add FRAUD_LOCK and is_blocked

Revision ID: ae664b7fdffb
Revises: 63480e3e0d3f
Create Date: 2026-08-30 16:41:07.715747

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae664b7fdffb'
down_revision: Union[str, Sequence[str], None] = '63480e3e0d3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customers', sa.Column('is_blocked', sa.Boolean(), nullable=True))
    op.execute("UPDATE customers SET is_blocked = false")
    op.alter_column('customers', 'is_blocked', nullable=False)
    with op.get_context().autocommit_block():
        op.execute("ALTER TYPE actiontype ADD VALUE 'FRAUD_LOCK'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customers', 'is_blocked')
    # ### end Alembic commands ###
