"""Initial models

Revision ID: eab3de4c1887
Revises: 
Create Date: 2026-08-30 15:29:12.783789

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eab3de4c1887'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('merchants',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('razorpay_key_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('webhook_events',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('event_id', sa.String(), nullable=False),
    sa.Column('event_type', sa.String(), nullable=False),
    sa.Column('payload_hash', sa.String(), nullable=False),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('received_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id', name='uq_webhook_event_id')
    )
    op.create_table('customers',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('contact', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('successful_payments_count', sa.Integer(), nullable=False),
    sa.Column('failed_payments_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('merchant_policies',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('max_automated_amount', sa.Integer(), nullable=False),
    sa.Column('max_recovery_attempts', sa.Integer(), nullable=False),
    sa.Column('allowed_actions', sa.String(), nullable=False),
    sa.Column('high_risk_requires_approval', sa.Boolean(), nullable=False),
    sa.Column('approval_threshold', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('orders',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('receipt', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_order_id')
    )
    op.create_table('payments',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('razorpay_payment_id', sa.String(), nullable=True),
    sa.Column('razorpay_order_id', sa.String(), nullable=True),
    sa.Column('order_id', sa.String(), nullable=True),
    sa.Column('customer_id', sa.String(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('method', sa.String(), nullable=True),
    sa.Column('failure_reason', sa.String(), nullable=True),
    sa.Column('error_code', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('razorpay_payment_id')
    )
    op.create_table('payment_attempts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('order_id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=True),
    sa.Column('attempt_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_cases',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('payment_id', sa.String(), nullable=False),
    sa.Column('merchant_id', sa.String(), nullable=False),
    sa.Column('amount_at_risk', sa.Integer(), nullable=False),
    sa.Column('recovery_probability', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='risklevel'), nullable=True),
    sa.Column('recommended_action', sa.Enum('RETRY_RECOVERY', 'PAYMENT_REMINDER', 'PAYMENT_LINK', 'ALTERNATIVE_PATH', 'ESCALATE', 'NO_ACTION', name='actiontype'), nullable=True),
    sa.Column('approved_action', sa.Enum('RETRY_RECOVERY', 'PAYMENT_REMINDER', 'PAYMENT_LINK', 'ALTERNATIVE_PATH', 'ESCALATE', 'NO_ACTION', name='actiontype'), nullable=True),
    sa.Column('status', sa.Enum('OPEN', 'ANALYZING', 'ACTION_PENDING', 'APPROVAL_REQUIRED', 'IN_PROGRESS', 'RECOVERED', 'FAILED', 'ESCALATED', 'NO_ACTION', name='recoverystatus'), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('is_demo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['merchant_id'], ['merchants.id'], ),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('agent_actions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recovery_case_id', sa.String(), nullable=False),
    sa.Column('action_type', sa.Enum('RETRY_RECOVERY', 'PAYMENT_REMINDER', 'PAYMENT_LINK', 'ALTERNATIVE_PATH', 'ESCALATE', 'NO_ACTION', name='actiontype'), nullable=False),
    sa.Column('confidence', sa.Numeric(precision=4, scale=3), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('policy_result', sa.String(), nullable=False),
    sa.Column('policy_notes', sa.Text(), nullable=True),
    sa.Column('execution_status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('recovery_results',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('recovery_case_id', sa.String(), nullable=False),
    sa.Column('amount_at_risk', sa.Integer(), nullable=False),
    sa.Column('amount_recovered', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('recovery_time_seconds', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['recovery_case_id'], ['recovery_cases.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recovery_case_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('recovery_results')
    op.drop_table('agent_actions')
    op.drop_table('recovery_cases')
    op.drop_table('payment_attempts')
    op.drop_table('payments')
    op.drop_table('orders')
    op.drop_table('merchant_policies')
    op.drop_table('customers')
    op.drop_table('webhook_events')
    op.drop_table('merchants')
    # ### end Alembic commands ###
